name: Release

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Rust toolchain 
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Use cache for Rust dependencies
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release && mv target/release/reshape ./reshape-linux_amd64
    - name: Save binary to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: reshape-linux_amd64

  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Log in to Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p $DOCKER_PASSWORD
    - name: Build Docker image
      # GITHUB_REF is formatted as: refs/tags/v0.0.1
      # The shell expansion used below will remove everything up to the version number, leaving 0.0.1
      run: docker build . --tag ${{ secrets.DOCKER_USER }}/reshape:${GITHUB_REF##*/v}
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/reshape