name: Release

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: linux_amd64
          target: x86_64-unknown-linux-gnu
        - name: macos_amd64
          target: x86_64-apple-darwin
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Rust toolchain 
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: ${{ matrix.target }}
    - name: Use cache for Rust dependencies
      uses: Swatinem/rust-cache@v1
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
        use-cross: true
    - name: Rename binary
      run: mv target/release/reshape ./reshape-${{ matrix.name }}
    - name: Save binary to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: reshape-${{ matrix.name }}

  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Log in to Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p $DOCKER_PASSWORD
    - name: Build Docker image
      # GITHUB_REF is formatted as: refs/tags/v0.0.1
      # The shell expansion used below will remove everything up to the version number, leaving 0.0.1
      run: docker build . --tag ${{ secrets.DOCKER_USER }}/reshape:${GITHUB_REF##*/v} --tag ${{ secrets.DOCKER_USER }}/reshape:latest
    - name: Push Docker image
      run: docker push --all-tags ${{ secrets.DOCKER_USER }}/reshape